version: '3.9'

services:
  db:
    image: postgres:14
    container_name: truecaller_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin404
      POSTGRES_DB: Truecaller_Based_JWT_db
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: Auth_flow_api
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data:
